apiVersion: skaffold/v1
kind: Config
metadata:
  name: app
deploy:
  kubectl:
    manifests:
    - k8s/apps.yml
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
  - image: discoenv/apps
  local: {}
